# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XGbfH9yn9_C1urhHGSh-dDY47b13cP2
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import numpy as np

# ==========================================
# 1. CONFIGURACIÓN DE LA PÁGINA
# ==========================================
st.set_page_config(
    page_title="TrustGuard - Caso Cancelado",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ==========================================
# 2. CARGA Y PROCESAMIENTO DE DATOS (PIPELINE)
# ==========================================
@st.cache_data
def load_and_process_data():
    # Carga de datos crudos
    df = pd.read_csv("BASE.csv")

    # Limpieza de valores nulos (Nivel Inicial)
    df['Antigüedad_Cuenta_Dias'] = df['Antigüedad_Cuenta_Dias'].fillna(df['Antigüedad_Cuenta_Dias'].median())
    df['Num_Interacciones'] = df['Num_Interacciones'].fillna(0)
    df['Fecha_Hora_Publicacion'] = pd.to_datetime(df['Fecha_Hora_Publicacion'])

    # Ingeniería de Features (Nivel Intermedio): Índice de Sospecha
    dias_seguros = df['Antigüedad_Cuenta_Dias'].replace(0, 0.5)
    df['Score_Sospecha'] = (df['Velocidad_Viralizacion'] / dias_seguros) * 100
    df['Score_Sospecha'] = np.clip(df['Score_Sospecha'], 0, 100)

    # Modelo de Clasificación (Nivel Avanzado): Semáforo de Confiabilidad
    condiciones = [
        (df['Contenido_Reciclado'] == 'Sí') | (df['Perfil_Usuario'] == 'Bot_Sospechoso') | (df['Score_Sospecha'] > 75),
        (df['Score_Sospecha'] > 30) & (df['Score_Sospecha'] <= 75),
        (df['Score_Sospecha'] <= 30) & (df['Contenido_Reciclado'] != 'Sí')
    ]
    etiquetas = ['🔴 Rojo (Ruido Fabricado)', '🟡 Amarillo (Dudoso)', '🟢 Verde (Señal Real)']
    df['Veredicto'] = np.select(condiciones, etiquetas, default='🟡 Amarillo (Dudoso)')

    return df

# Cargar dataset procesado
try:
    df = load_and_process_data()
except Exception as e:
    st.error(f"Error al cargar el archivo BASE.csv. Asegúrate de que esté en la misma carpeta. Detalle: {e}")
    st.stop()

# ==========================================
# 3. BARRA LATERAL (FILTROS GLOBALES)
# ==========================================
st.sidebar.header("🎛️ Panel de Control")
st.sidebar.markdown("Filtra la evidencia analizada en tiempo real para la toma de decisiones.")

plataformas_sel = st.sidebar.multiselect("Plataforma:", df['Plataforma'].unique(), default=df['Plataforma'].unique())
perfiles_sel = st.sidebar.multiselect("Perfil de Usuario:", df['Perfil_Usuario'].unique(), default=df['Perfil_Usuario'].unique())
veredictos_sel = st.sidebar.multiselect("Veredicto Algorítmico:", df['Veredicto'].unique(), default=df['Veredicto'].unique())

# Filtrado dinámico
df_filtered = df[
    (df['Plataforma'].isin(plataformas_sel)) &
    (df['Perfil_Usuario'].isin(perfiles_sel)) &
    (df['Veredicto'].isin(veredictos_sel))
]

# ==========================================
# 4. ENCABEZADO Y KPIS PRINCIPALES
# ==========================================
st.title("🛡️ TrustGuard: Sistema de Detección de Señal vs Ruido")
st.markdown("**Caso:** Crisis digital de Kai Duarte | **Propósito:** Separar la evidencia genuina del ruido fabricado antes del cierre de contratos[cite: 1, 3].")

col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Registros Analizados", f"{len(df_filtered):,}")
col2.metric("Alertas Rojas (Ruido)", f"{len(df_filtered[df_filtered['Veredicto'] == '🔴 Rojo (Ruido Fabricado)']):,}")
col3.metric("Velocidad Máxima", f"{df_filtered['Velocidad_Viralizacion'].max():,.1f} ints/min")
col4.metric("Contenido Reciclado", f"{len(df_filtered[df_filtered['Contenido_Reciclado'] == 'Sí']):,}")

st.divider()

# ==========================================
# 5. PESTAÑAS DEL PROTOTIPO FUNCIONAL
# ==========================================
tab1, tab2, tab3, tab4 = st.tabs([
    "📊 Línea de Tiempo",
    "🔍 Auditoría Explicable (XAI)",
    "🗺️ Mapa de Coordinación",
    "📋 Base de Datos Cruda"
])

# --- PESTAÑA 1: LÍNEA DE TIEMPO ---
with tab1:
    st.subheader("Evolución Temporal del Escándalo")
    st.markdown("Visualiza los momentos clave de propagación y el ingreso masivo de cuentas sospechosas[cite: 2].")

    fig_timeline = px.histogram(
        df_filtered, x="Fecha_Hora_Publicacion", color="Veredicto",
        color_discrete_map={
            '🔴 Rojo (Ruido Fabricado)':'#ff4b4b',
            '🟡 Amarillo (Dudoso)':'#ffaa00',
            '🟢 Verde (Señal Real)':'#21c354'
        },
        nbins=60, hover_data=["Plataforma"]
    )
    fig_timeline.update_layout(xaxis_title="Fecha y Hora", yaxis_title="Volumen de Publicaciones", hovermode="x unified")
    st.plotly_chart(fig_timeline, use_container_width=True)

    c1, c2 = st.columns(2)
    with c1:
        fig_pie = px.pie(df_filtered, names='Plataforma', hole=0.4, title="Distribución por Red Social")
        st.plotly_chart(fig_pie, use_container_width=True)
    with c2:
        fig_bar = px.histogram(
            df_filtered, y="Perfil_Usuario", color="Veredicto", barmode="stack",
            color_discrete_map={
                '🔴 Rojo (Ruido Fabricado)':'#ff4b4b',
                '🟡 Amarillo (Dudoso)':'#ffaa00',
                '🟢 Verde (Señal Real)':'#21c354'
            },
            title="Veredicto según Tipo de Perfil de Usuario"
        )
        st.plotly_chart(fig_bar, use_container_width=True)

# --- PESTAÑA 2: AUDITORÍA EXPLICABLE (XAI) ---
with tab2:
    st.subheader("Explicabilidad del Modelo (XAI)")
    st.markdown("Selecciona una cuenta marcada como 'Rojo' para auditar las razones algorítmicas detrás del veredicto[cite: 2].")

    df_rojos = df[df['Veredicto'] == '🔴 Rojo (Ruido Fabricado)']
    if len(df_rojos) > 0:
        opciones = df_rojos['Usuario_Handle'].astype(str) + " (ID: " + df_rojos['ID_Publicacion'].astype(str) + ")"
        seleccion = st.selectbox("Seleccione cuenta sospechosa para inspeccionar:", opciones)

        if seleccion:
            id_sel = int(seleccion.split("(ID: ")[1].replace(")", ""))
            pub = df[df['ID_Publicacion'] == id_sel].iloc[0]

            st.info(f"**Texto / Evidencia Registrada:** *'{pub['Texto_Publicacion']}'*")

            # Desglose métrico de la decisión
            col_a, col_b, col_c = st.columns(3)
            col_a.metric("Mención / Usuario", pub['Usuario_Handle'], pub['Perfil_Usuario'])
            col_b.metric("Plataforma", pub['Plataforma'])
            col_c.metric("Veredicto Final", pub['Veredicto'])

            st.write("### Factores de Ponderación (Índice de Sospecha)")
            st.progress(int(pub['Score_Sospecha']), text=f"Puntaje de Anomalía: {int(pub['Score_Sospecha'])} / 100")

            m1, m2, m3 = st.columns(3)
            m1.metric("Antigüedad de Cuenta", f"{pub['Antigüedad_Cuenta_Dias']} días", "Alerta por cuenta nueva" if pub['Antigüedad_Cuenta_Dias'] < 10 else "Estable", delta_color="inverse")
            m2.metric("Velocidad de Viralización", f"{pub['Velocidad_Viralizacion']} ints/min", "Propagación anómala" if pub['Velocidad_Viralizacion'] > 5 else "Normal", delta_color="inverse")
            m3.metric("Contenido Reciclado", pub['Contenido_Reciclado'], "Plagio detectado" if pub['Contenido_Reciclado'] == 'Sí' else "Original", delta_color="inverse")
    else:
        st.warning("No hay registros bajo los filtros actuales que coincidan con Alertas Rojas.")

# --- PESTAÑA 3: MAPA DE COORDINACIÓN ---
with tab3:
    st.subheader("Detección de Coordinación y Cuentas Falsas")
    st.markdown("El **tamaño de la burbuja** representa el número de interacciones. Las burbujas grandes cerca del eje 0 (izquierda) delatan gran coordinación artificial[cite: 1, 2].")

    df_burbujas = df_filtered.copy()
    df_burbujas['Interacciones_Visual'] = df_burbujas['Num_Interacciones'].clip(lower=10)

    fig_scatter = px.scatter(
        df_burbujas, x="Antigüedad_Cuenta_Dias", y="Velocidad_Viralizacion",
        color="Veredicto", size="Interacciones_Visual",
        hover_data=["Usuario_Handle", "ID_Publicacion", "Num_Interacciones", "Plataforma"],
        color_discrete_map={
            '🔴 Rojo (Ruido Fabricado)':'#ff4b4b',
            '🟡 Amarillo (Dudoso)':'#ffaa00',
            '🟢 Verde (Señal Real)':'#21c354'
        },
        opacity=0.7, size_max=40
    )
    fig_scatter.add_hline(y=10, line_dash="dash", line_color="red", annotation_text="Umbral de Velocidad Sospechosa")
    st.plotly_chart(fig_scatter, use_container_width=True)

# --- PESTAÑA 4: EXPLORADOR DE DATOS ---
with tab4:
    st.subheader("Base de Datos Procesada")
    st.markdown("Consulta y exporta la tabla completa con las nuevas variables creadas por el equipo.")
    st.dataframe(
        df_filtered[['ID_Publicacion', 'Usuario_Handle', 'Plataforma', 'Perfil_Usuario', 'Texto_Publicacion', 'Veredicto', 'Score_Sospecha', 'Velocidad_Viralizacion']],
        use_container_width=True, height=450
    )